---
- name: Authbind package to be installed.
  ansible.builtin.apt:
    name: authbind

- name: Create files which needs to be bound.
  ansible.builtin.file:
    path: "{{ '/etc/authbind/byport/' + item | string }}"
    owner: "{{ authbind.user }}"
    group: "{{ authbind.group }}"
    mode: '0700'
    state: 'touch'
  with_items: "{{ authbind.ports }}"
