---
- name: Fail if required IP variables are not set
  fail:
    msg: "{{ item }} variable is not defined. Please check container IP setup."
  when: vars[item] | default('') == ''
  loop: "{{ required_ips }}"

- name: Install BIND9
  apt:
    name: bind9
    state: present

- name: Configure BIND9 forward Zone
  template:
    src: db.jdevlab.local.j2
    dest: /etc/bind/db.jdev.lab
  notify: Restart BIND service

- name: Configure BIND9 revere Zone
  template:
    src: db.192.168.1.j2
    dest: /etc/bind/db.192.168.1
  notify: Restart BIND service

- name: Configure named.conf.local
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart BIND service
