---
default_language_version:
    python: python3.12.0
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [ "-d", "{extends: relaxed, rules: {line-length: {max: 120}}}" ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-byte-order-marker
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.6.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
  - repo: local
    hooks:
    - id: poetry-check
      name: poetry-check
      description: run poetry check to validate config
      entry: poetry check
      language: python
      pass_filenames: false
      files: ^(.*/)?(poetry\.lock|pyproject\.toml)$

    - id: poetry-lock
      name: poetry-lock
      description: run poetry lock to update lock file
      entry: poetry lock
      language: python
      pass_filenames: false
      files: ^(.*/)?(poetry\.lock|pyproject\.toml)$

    - id: poetry-export
      name: poetry-export
      description: run poetry export to sync lock file with requirements.txt
      entry: poetry export
      language: python
      pass_filenames: false
      files: ^(.*/)?poetry\.lock$
      args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]

    - id: poetry-export-dev
      name: poetry-export dev
      description: run poetry export to sync lock file with requirements-dev.txt
      entry: poetry export
      language: python
      pass_filenames: false
      files: ^(.*/)?poetry\.lock$
      args: ["-f", "requirements.txt", "-o", "requirements-dev.txt", "--without-hashes", "--with", "dev,test"]

    - id: poetry-install
      name: poetry-install
      description: run poetry install to install dependencies from the lock file
      entry: poetry install
      language: python
      pass_filenames: false
      stages: [post-checkout, post-merge]
      always_run: true
