version: "3.9"

services:
  ubuntu20:
    networks:
      - production 

  ubuntu22:
    networks:
      - production 

  ubuntu18:
    networks:
      - production 

networks:
  production:
    name: production