version: "3.9"

services:
  ubuntu20:
    hostname: uat01
    environment:
      env_type: uat
    networks:
      - uat

  ubuntu22:
    hostname: uat02
    environment:
      env_type: uat
    networks:
      - uat

  ubuntu18:
    hostname: uat03
    environment:
      env_type: uat
    networks:
      - uat

networks:
  uat:
    name: uat
