version: "3.9"

services:
  ubuntu20:
    hostname: stage01
    environment:
      env_type: stage
    networks:
      - stage

  ubuntu22:
    hostname: stage02
    environment:
      env_type: stage
    networks:
      - stage

  ubuntu18:
    hostname: stage03
    environment:
      env_type: stage
    networks:
      - stage

networks:
  stage:
    name: stage
