services:
  ubuntu20:
    hostname: test20
    environment:
      env_type: test
    build:
      labels:
        evironment_owner: "qa"
        billing.owner: "qa-goverance"

  ubuntu22:
    hostname: test22
    environment:
      env_type: test
    build:
      labels:
        evironment_owner: "qa"
        billing.owner: "qa-goverance"

  ubuntu23:
    hostname: test23
    environment:
      env_type: test
    build:
      labels:
        evironment_owner: "qa"
        billing.owner: "qa-goverance"

  ubuntu24:
    hostname: test24
    environment:
      env_type: test
    build:
      labels:
        evironment_owner: "qa"
        billing.owner: "qa-goverance"
