version: "3.9"

services:
  ubuntu20:
    hostname: prod01
    environment:
      env_type: prod
    networks:
      - prod

  ubuntu22:
    hostname: prod02
    environment:
      env_type: prod
    networks:
      - prod

  ubuntu18:
    hostname: prod03
    environment:
      env_type: prod
    networks:
      - prod

networks:
  prod:
    name: prod
