services:
  ubuntu20:
    image: jojees/ubuntu:20.04
    tty: True
    build:
      labels:
        application.group: "vanilla"
        application.age: "moderate"
        maintenance.owner: "Engineering"
        billing.owner: "Engineering"
        environment_group: "lab"
      context: .
      dockerfile: Dockerfile-ubuntu20.04

  ubuntu22:
    image: jojees/ubuntu:22.04
    tty: True
    build:
      labels:
        application.group: "vanilla"
        application.age: "low"
        maintenance.owner: "Engineering"
        billing.owner: "Engineering"
        environment_group: "lab"
      context: .
      dockerfile: Dockerfile-ubuntu22.04
    stop_grace_period: 1s

  ubuntu23:
    image: jojees/ubuntu:23.04
    tty: True
    build:
      labels:
        application.group: "vanilla"
        application.age: "low"
        maintenance.owner: "Engineering"
        billing.owner: "Engineering"
        environment_group: "lab"
      context: .
      dockerfile: Dockerfile-ubuntu23.04
    stop_grace_period: 1s

  ubuntu24:
    image: jojees/ubuntu:24.04
    tty: True
    build:
      labels:
        application.group: "vanilla"
        application.age: "low"
        maintenance.owner: "Engineering"
        billing.owner: "Engineering"
        environment_group: "lab"
      context: .
      dockerfile: Dockerfile-ubuntu24.04
    stop_grace_period: 1s
