Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
    config.vm.define "ubuntu20"
    config.vm.hostname = "workstation"
    config.vm.provider :virtualbox do |vb|
        vb.name = "ubuntu20"
    end
    config.vm.network "private_network", ip: "192.168.33.19"
    # config.vm.network "public_network",
    #   use_dhcp_assigned_default_route: true
 
    config.vm.provider "virtualBox" do |vb|
      vb.gui = true
      vb.memory = "1024"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "../ansible/setup.yaml"
    end
 
    # config.vm.provision "shell", inline: <<-SHELL
    #   apt-get update
    #   apt-get install \
    #   apt-transport-https \
    #   ca-certificates \
    #   curl vim net-tools \
    #   software-properties-common -y
    # SHELL
 end