---
default_packages:
  - apt-transport-https
  - ca-certificates 
  - curl 
  - gnupg-agent
  - software-properties-common
  - vim
  - net-tools
  - wget

cache_valid_time: 604800

application_user: japps
users:
  primary:
    - root
    - ubuntu
  vagrant:
    - vagrant
  applications:
    - "{{ application_user }}"

authbind:
  user: "{{ application_user }}"
  group: "{{ application_user }}"
  ports:
    - 25
    - 80
    - 443