---
system_defaults_default_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - vim
  - net-tools
  - wget

system_defaults_cache_valid_time: 604800

system_defaults_application_user: japps
system_defaults_users:
  primary:
    - root
    - ubuntu
  vagrant:
    - vagrant
  applications:
    - "{{ application_user }}"

system_defaults_authbind:
  user: "{{ application_user }}"
  group: "{{ application_user }}"
  ports:
    - 25
    - 80
    - 443
