---
- name: Install packages needed on workstation
  community.general.homebrew:
    name: "{{ workstation_packages }}"
    state: latest
    update_homebrew: true

- name: Installing Ansible Collections using requirements.yml
  community.buitin.command: ansible-galaxy collection install -r ../requirements.yaml
