---
- name: Update bash profile for users.
  ansible.builtin.template:
    src: files/custom_profile
    dest: "/etc/profile.d/X99-custom-profile"
    owner: "root"
    group: "root"
    mode: '0644'
