---
- name: Add .vimrc configuration to skell directory.
  ansible.builtin.template:
    src: files/vimrc
    dest: /etc/skel/.vimrc
    mode: '0644'

- name: Add primary users to default users list.
  ansible.builtin.set_fact:
    default_users: "{{ users.primary }}"

- name: Check for default sudo user.
  ansible.builtin.debug:
    var: ansible_facts['env']['SUDO_USER']

- name: Add vagrant user to default users list.
  ansible.builtin.set_fact:
    default_users: "{{ users.primary + users.vagrant }}"
  when: ansible_facts['env']['SUDO_USER'] == 'vagrant'

- name: Add .vimrc configuration file for default users.
  ansible.builtin.template:
    src: files/vimrc
    dest: "{{ '~' + item + '/.vimrc' }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  with_items: "{{ default_users }}"
