---
- name: Start required containers
  hosts: jdevlab
  tags: always
  tasks:
    - name: Install provisioning dependencies
      ansible.builtin.apt:
        name: python3-lxc
        state: present

    - name: Create required containers
      community.general.lxd_container:
        name: "{{ item.name }}"
        ignore_volatile_options: true
        state: started
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases/
          protocol: simplestreams
          alias: "{{ item.alias }}"
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        wait_for_container: true
        timeout: 600
      loop: "{{ service_containers }}"
      register: service_containers_results
      run_once: true

    - name: Add containers to inventory
      ansible.builtin.add_host:
        name: "{{ item.item.name }}"
        groups: containers
        ansible_connection: "{{ ansible_container_connection }}"
        ansible_lxd_remote: "{{ lxd_remote_name }}"
      loop: "{{ service_containers_results.results }}"

    - name: Set IP addresses of all containers as facts
      ansible.builtin.set_fact:
        container_ips: "{{ container_ips | default({}) | combine({ item.item.name: item.addresses.eth0[0]}) }}"
      loop: "{{ service_containers_results.results }}"
      when: item.addresses | length > 0
      run_once: true

    - name: Add containers IPv4 address's to a dummy host variable
      ansible.builtin.add_host:
        name: "CONTAINERS_IP_HOLDER"
        container_ips: "{{ container_ips }}"

- name: Ensure python is installed on the containers
  hosts: containers
  gather_facts: false
  tags: always
  tasks:
    - name: Check python is installed in container
      ansible.builtin.raw: dpkg -s python
      register: python_install_check
      failed_when: python_install_check.rc not in [0, 1]
      changed_when: false

    - name: Install python in container
      ansible.builtin.raw: apt-get install -y python3
      when: python_install_check.rc == 1
      changed_when: false

- name: Setup bind9 for the lab
  hosts: dnsbind9
  gather_facts: false
  become: true
  tags:
    - bind9
  roles:
    - role: bind9

# - name: Setup sendmail and Dovecot for the lab
#   hosts: mail1
#   gather_facts: false
#   become: true
#   tags:
#     - sendmail
#   roles:
#     - role: sendmail

- name: Setup contianers system level configs
  hosts: containers
  gather_facts: false
  roles:
    - role: baseline_configuration

- name: Stop the lab environment
  hosts: jdevlab
  tags: never
  tasks:
    - name: Shutting down the lab servers
      community.general.shutdown:
